export const mockUser = {
  login: "torvalds",
  name: "Linus Torvalds",
  avatar_url: "https://avatars.githubusercontent.com/u/1024025?v=4",
  bio: "Full-stack engineer and open source maintainer",
  location: "Portland, OR",
  public_repos: 24,
  followers: 1200,
  following: 89,
};

export const mockRepos = [
  {
    id: 1,
    name: "ui-kit",
    description: "A modern UI component library",
    stargazers_count: 1200,
    forks_count: 234,
    language: "TypeScript",
    visibility: "public",
    updated_at: "2024-01-01",
    html_url: "https://github.com",
  },
  {
    id: 2,
    name: "cli-tool",
    description: "Command line interface tool",
    stargazers_count: 340,
    forks_count: 56,
    language: "Rust",
    visibility: "private",
    updated_at: "2024-01-15",
    html_url: "https://github.com",
  },
  {
    id: 3,
    name: "design-system",
    description: "Design system and tokens",
    stargazers_count: 45,
    forks_count: 12,
    language: "CSS",
    visibility: "public",
    updated_at: "2024-02-01",
    html_url: "https://github.com",
  },
];
